### ISSUE TITLE
Make sure that the login procedure does not throw raw errors

### ISSUE THREAD

**Issue by gear54rus** [gear54rus/skype-undelete-bot#4]
Like these (seen in db66f9d):
```
Unhandled rejection Error: Login failed: Cannot read property '1' of null. Check your credentials at https://web.skype.com/en/.
    at request.then.then.then.then.then.then.catch.e (/root/skype-undelete-bot/src/session.js:140:27)
    at tryCatcher (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/root/.nvm/versions/node/v7.3.0/lib/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

User needs to be told exactly what happened, inputs need to be sanitized.

**Comment by gear54rus** [comment]
Also, replace all numeric HTTP codes with constants.
